import { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "1",
    name: "Nike Air Max 90",
    description: "Classic Nike sneakers with Air cushioning for all-day comfort.",
    price: 120,
    originalPrice: 150,
    images: ["https://placehold.co/400x400?text=Nike+Air+Max"],
    brand: "Nike",
    category: "Footwear",
    subcategory: "Sneakers",
    sku: "NK-AM90-001",
    availability: "in_stock",
    rating: { average: 4.7, count: 2341 },
    attributes: { color: "white", size: "42", material: "mesh" },
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Apple MacBook Pro 14",
    description: "Powerful laptop with M3 chip, perfect for developers and designers.",
    price: 1999,
    images: ["https://placehold.co/400x400?text=MacBook+Pro"],
    brand: "Apple",
    category: "Electronics",
    subcategory: "Laptops",
    sku: "APL-MBP14-001",
    availability: "in_stock",
    rating: { average: 4.9, count: 876 },
    attributes: { color: "silver", diagonal: 14, ram: 16, storage: 512 },
    createdAt: "2024-03-10T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Levi's 501 Original Jeans",
    description: "Iconic straight-fit jeans made from 100% cotton denim.",
    price: 89,
    originalPrice: 110,
    images: ["https://placehold.co/400x400?text=Levis+501"],
    brand: "Levi's",
    category: "Clothing",
    subcategory: "Jeans",
    sku: "LV-501-001",
    availability: "in_stock",
    rating: { average: 4.5, count: 5120 },
    attributes: { color: "blue", size: "32x32", material: "cotton" },
    createdAt: "2024-02-20T00:00:00Z",
    updatedAt: "2024-05-15T00:00:00Z",
  },
  {
    id: "4",
    name: "Samsung Galaxy S24",
    description: "Flagship smartphone with stunning display and powerful performance.",
    price: 999,
    images: ["https://placehold.co/400x400?text=Galaxy+S24"],
    brand: "Samsung",
    category: "Electronics",
    subcategory: "Smartphones",
    sku: "SMS-GS24-001",
    availability: "pre_order",
    rating: { average: 4.8, count: 432 },
    attributes: { color: "black", storage: 256, ram: 12 },
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "5",
    name: "Sony WH-1000XM4",
    description: "Industry-leading noise-canceling headphones with exceptional sound quality.",
    price: 349,
    originalPrice: 399,
    images: ["https://placehold.co/400x400?text=Sony+WH1000XM4"],
    brand: "Sony",
    category: "Electronics",
    subcategory: "Headphones",
    sku: "SNY-WH1000XM4-001",
    availability: "in_stock",
    rating: { average: 4.9, count: 3210 },
    attributes: { color: "black", batteryLife: "30h", wireless: true },
    createdAt: "2024-01-25T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "6",
    name: "Adidas Ultraboost 22",
    description: "High-performance running shoes with responsive Boost cushioning.",
    price: 180,
    images: ["https://placehold.co/400x400?text=Adidas+Ultraboost"],
    brand: "Adidas",
    category: "Footwear",
    subcategory: "Running Shoes",
    sku: "ADS-UB22-001",
    availability: "out_of_stock",
    rating: { average: 4.6, count: 1540 },
    attributes: { color: "black", size: "42", material: "knit" },
    createdAt: "2024-02-10T00:00:00Z",
    updatedAt: "2024-05-20T00:00:00Z",
  },
  {
    id: "7",
    name: "The North Face Borealis Backpack",
    description: "Durable and spacious backpack perfect for everyday use and outdoor adventures.",
    price: 99,
    images: ["https://placehold.co/400x400?text=North+Face+Borealis"],
    brand: "The North Face",
    category: "Accessories",
    subcategory: "Backpacks",
    sku: "TNF-BOR-001",
    availability: "in_stock",
    rating: { average: 4.7, count: 890 },
    attributes: { color: "gray", capacity: "28L", material: "nylon" },
    createdAt: "2024-03-05T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "8",
    name: "Canon EOS R5",
    description: "Professional mirrorless camera with 45MP sensor and 8K video recording.",
    price: 3899,
    images: ["https://placehold.co/400x400?text=Canon+EOS+R5"],
    brand: "Canon",
    category: "Electronics",
    subcategory: "Cameras",
    sku: "CAN-EOSR5-001",
    availability: "in_stock",
    rating: { average: 4.9, count: 210 },
    attributes: { color: "black", sensorResolution: "45MP", videoResolution: "8K" },
    createdAt: "2024-04-15T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "9",
    name: "Patagonia Better Sweater Fleece Jacket",
    description: "Warm and cozy fleece jacket made from recycled materials.",
    price: 139,
    images: ["https://placehold.co/400x400?text=Patagonia+Better+Sweater"],
    brand: "Patagonia",
    category: "Clothing",
    subcategory: "Jackets",
    sku: "PAT-BSF-001",
    availability: "in_stock",
    rating: { average: 3.5, count: 670 },
    attributes: { color: "green", size: "M", material: "fleece" },
    createdAt: "2024-02-28T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  }
];

export const categories = Array.from(new Set(products.map((p) => p.category)));

export const ratings = Array.from(new Set(products.map((p) => Math.floor(p.rating.average))));

export const sortOptions = [
  { label: "Price: Low to High", value: "price_asc" },
  { label: "Price: High to Low", value: "price_desc" },
  { label: "Rating: High to Low", value: "rating_desc" },
  { label: "Newest Arrivals", value: "newest" },
];

export const brands = Array.from(new Set(products.map((p) => p.brand)));

export const colors = Array.from(new Set(products.map((p) => p.attributes.color)));
