import { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "1",
    name: "Nike Air Max 90",
    description: "Classic Nike sneakers with Air cushioning for all-day comfort.",
    price: 120,
    originalPrice: 150,
    images: ["https://placehold.co/400x400?text=Nike+Air+Max"],
    brand: "Nike",
    category: "Footwear",
    subcategory: "Sneakers",
    sku: "NK-AM90-001",
    availability: "in_stock",
    rating: { average: 4.7, count: 2341 },
    attributes: { color: "white", size: "42", material: "mesh" },
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Apple MacBook Pro 14",
    description: "Powerful laptop with M3 chip, perfect for developers and designers.",
    price: 1999,
    images: ["https://placehold.co/400x400?text=MacBook+Pro"],
    brand: "Apple",
    category: "Electronics",
    subcategory: "Laptops",
    sku: "APL-MBP14-001",
    availability: "in_stock",
    rating: { average: 4.9, count: 876 },
    attributes: { color: "silver", diagonal: 14, ram: 16, storage: 512 },
    createdAt: "2024-03-10T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Levi's 501 Original Jeans",
    description: "Iconic straight-fit jeans made from 100% cotton denim.",
    price: 89,
    originalPrice: 110,
    images: ["https://placehold.co/400x400?text=Levis+501"],
    brand: "Levi's",
    category: "Clothing",
    subcategory: "Jeans",
    sku: "LV-501-001",
    availability: "in_stock",
    rating: { average: 4.5, count: 5120 },
    attributes: { color: "blue", size: "32x32", material: "cotton" },
    createdAt: "2024-02-20T00:00:00Z",
    updatedAt: "2024-05-15T00:00:00Z",
  },
  {
    id: "4",
    name: "Samsung Galaxy S24",
    description: "Flagship smartphone with stunning display and powerful performance.",
    price: 999,
    images: ["https://placehold.co/400x400?text=Galaxy+S24"],
    brand: "Samsung",
    category: "Electronics",
    subcategory: "Smartphones",
    sku: "SMS-GS24-001",
    availability: "pre_order",
    rating: { average: 4.8, count: 432 },
    attributes: { color: "black", storage: 256, ram: 12 },
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "5",
    name: "Sony WH-1000XM4",
    description: "Industry-leading noise-canceling headphones with exceptional sound quality.",
    price: 349,
    originalPrice: 399,
    images: ["https://placehold.co/400x400?text=Sony+WH1000XM4"],
    brand: "Sony",
    category: "Electronics",
    subcategory: "Headphones",
    sku: "SNY-WH1000XM4-001",
    availability: "in_stock",
    rating: { average: 4.9, count: 3210 },
    attributes: { color: "black", batteryLife: "30h", wireless: true },
    createdAt: "2024-01-25T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "6",
    name: "Adidas Ultraboost 22",
    description: "High-performance running shoes with responsive Boost cushioning.",
    price: 180,
    images: ["https://placehold.co/400x400?text=Adidas+Ultraboost"],
    brand: "Adidas",
    category: "Footwear",
    subcategory: "Running Shoes",
    sku: "ADS-UB22-001",
    availability: "out_of_stock",
    rating: { average: 4.6, count: 1540 },
    attributes: { color: "black", size: "42", material: "knit" },
    createdAt: "2024-02-10T00:00:00Z",
    updatedAt: "2024-05-20T00:00:00Z",
  },
  {
    id: "7",
    name: "The North Face Borealis Backpack",
    description: "Durable and spacious backpack perfect for everyday use and outdoor adventures.",
    price: 99,
    images: ["https://placehold.co/400x400?text=North+Face+Borealis"],
    brand: "The North Face",
    category: "Accessories",
    subcategory: "Backpacks",
    sku: "TNF-BOR-001",
    availability: "in_stock",
    rating: { average: 4.7, count: 890 },
    attributes: { color: "gray", capacity: "28L", material: "nylon" },
    createdAt: "2024-03-05T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "8",
    name: "Canon EOS R5",
    description: "Professional mirrorless camera with 45MP sensor and 8K video recording.",
    price: 3899,
    images: ["https://placehold.co/400x400?text=Canon+EOS+R5"],
    brand: "Canon",
    category: "Electronics",
    subcategory: "Cameras",
    sku: "CAN-EOSR5-001",
    availability: "in_stock",
    rating: { average: 4.9, count: 210 },
    attributes: { color: "black", sensorResolution: "45MP", videoResolution: "8K" },
    createdAt: "2024-04-15T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "9",
    name: "Patagonia Better Sweater Fleece Jacket",
    description: "Warm and cozy fleece jacket made from recycled materials.",
    price: 139,
    images: ["https://placehold.co/400x400?text=Patagonia+Better+Sweater"],
    brand: "Patagonia",
    category: "Clothing",
    subcategory: "Jackets",
    sku: "PAT-BSF-001",
    availability: "in_stock",
    rating: { average: 3.5, count: 670 },
    attributes: { color: "green", size: "M", material: "fleece" },
    createdAt: "2024-02-28T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "10",
    name: "Google Pixel 8 Pro",
    description: "Flagship smartphone with advanced AI features and stunning camera capabilities.",
    price: 899,
    images: ["https://placehold.co/400x400?text=Pixel+8+Pro"],
    brand: "Google",
    category: "Electronics",
    subcategory: "Smartphones",
    sku: "GOO-PX8P-001",
    availability: "in_stock",
    rating: { average: 4.8, count: 540 },
    attributes: { color: "white", storage: 128, ram: 12 },
    createdAt: "2024-05-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "11",
    name: "IKEA BILLY Bookcase",
    description: "Classic bookcase with adjustable shelves, perfect for any room.",
    price: 79,
    images: ["https://placehold.co/400x400?text=IKEA+BILLY"],
    brand: "IKEA",
    category: "Home",
    subcategory: "Furniture",
    sku: "IKE-BILLY-001",
    availability: "in_stock",
    rating: { average: 4.3, count: 8920 },
    attributes: { color: "white", material: "wood", size: "80x28x202cm" },
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "12",
    name: "Dyson V15 Detect",
    description: "Powerful cordless vacuum with laser dust detection technology.",
    price: 749,
    originalPrice: 849,
    images: ["https://placehold.co/400x400?text=Dyson+V15"],
    brand: "Dyson",
    category: "Home",
    subcategory: "Appliances",
    sku: "DYS-V15-001",
    availability: "in_stock",
    rating: { average: 4.8, count: 1230 },
    attributes: { color: "yellow", material: "plastic", batteryLife: "60min" },
    createdAt: "2024-02-15T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "13",
    name: "New Balance 990v6",
    description: "Premium running shoe made in USA with superior cushioning.",
    price: 185,
    images: ["https://placehold.co/400x400?text=NB+990v6"],
    brand: "New Balance",
    category: "Footwear",
    subcategory: "Running Shoes",
    sku: "NB-990V6-001",
    availability: "in_stock",
    rating: { average: 4.7, count: 654 },
    attributes: { color: "gray", size: "42", material: "mesh" },
    createdAt: "2024-03-20T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "14",
    name: "Kindle Paperwhite",
    description: "Waterproof e-reader with adjustable warm light and 3 months battery life.",
    price: 139,
    originalPrice: 159,
    images: ["https://placehold.co/400x400?text=Kindle+Paperwhite"],
    brand: "Amazon",
    category: "Electronics",
    subcategory: "E-Readers",
    sku: "AMZ-KPW-001",
    availability: "in_stock",
    rating: { average: 4.6, count: 12400 },
    attributes: { color: "black", storage: 8, batteryLife: "10weeks" },
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "15",
    name: "Uniqlo Ultra Light Down Jacket",
    description: "Lightweight packable down jacket that folds into its own pocket.",
    price: 69,
    images: ["https://placehold.co/400x400?text=Uniqlo+Down"],
    brand: "Uniqlo",
    category: "Clothing",
    subcategory: "Jackets",
    sku: "UNI-ULD-001",
    availability: "in_stock",
    rating: { average: 4.5, count: 3210 },
    attributes: { color: "black", size: "M", material: "down" },
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "16",
    name: "GoPro HERO12 Black",
    description: "Waterproof action camera with 5.3K video and HyperSmooth stabilization.",
    price: 399,
    originalPrice: 449,
    images: ["https://placehold.co/400x400?text=GoPro+HERO12"],
    brand: "GoPro",
    category: "Electronics",
    subcategory: "Cameras",
    sku: "GPR-H12-001",
    availability: "in_stock",
    rating: { average: 4.7, count: 890 },
    attributes: { color: "black", videoResolution: "5.3K", waterproof: true },
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "17",
    name: "Lululemon Align Leggings",
    description: "Buttery soft yoga leggings with 4-way stretch fabric.",
    price: 98,
    images: ["https://placehold.co/400x400?text=Lululemon+Align"],
    brand: "Lululemon",
    category: "Clothing",
    subcategory: "Sportswear",
    sku: "LUL-ALN-001",
    availability: "in_stock",
    rating: { average: 4.8, count: 5670 },
    attributes: { color: "black", size: "S", material: "nylon" },
    createdAt: "2024-03-10T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "18",
    name: "Weber Spirit II E-310",
    description: "3-burner gas grill with GS4 grilling system and iGrill compatibility.",
    price: 499,
    images: ["https://placehold.co/400x400?text=Weber+Spirit"],
    brand: "Weber",
    category: "Home",
    subcategory: "Outdoor",
    sku: "WBR-SP2-001",
    availability: "in_stock",
    rating: { average: 4.6, count: 2340 },
    attributes: { color: "black", material: "steel", size: "44000BTU" },
    createdAt: "2024-04-15T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "19",
    name: "Fitbit Charge 6",
    description: "Advanced fitness tracker with built-in GPS and heart rate monitoring.",
    price: 159,
    originalPrice: 179,
    images: ["https://placehold.co/400x400?text=Fitbit+Charge6"],
    brand: "Fitbit",
    category: "Electronics",
    subcategory: "Wearables",
    sku: "FBT-CH6-001",
    availability: "in_stock",
    rating: { average: 4.4, count: 1890 },
    attributes: { color: "black", batteryLife: "7days", waterproof: true },
    createdAt: "2024-05-10T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "20",
    name: "Osprey Atmos AG 65",
    description: "Award-winning hiking backpack with Anti-Gravity suspension system.",
    price: 290,
    images: ["https://placehold.co/400x400?text=Osprey+Atmos"],
    brand: "Osprey",
    category: "Accessories",
    subcategory: "Backpacks",
    sku: "OSP-ATM65-001",
    availability: "out_of_stock",
    rating: { average: 4.9, count: 432 },
    attributes: { color: "gray", capacity: "65L", material: "nylon" },
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "21",
    name: "iPad Pro 12.9",
    description: "Most powerful iPad with M2 chip, Liquid Retina XDR display.",
    price: 1099,
    images: ["https://placehold.co/400x400?text=iPad+Pro"],
    brand: "Apple",
    category: "Electronics",
    subcategory: "Tablets",
    sku: "APL-IPP129-001",
    availability: "in_stock",
    rating: { average: 4.9, count: 3210 },
    attributes: { color: "silver", storage: 256, ram: 8 },
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "22",
    name: "Nike Dri-FIT T-Shirt",
    description: "Moisture-wicking athletic t-shirt for training and running.",
    price: 35,
    images: ["https://placehold.co/400x400?text=Nike+DryFit"],
    brand: "Nike",
    category: "Clothing",
    subcategory: "Sportswear",
    sku: "NK-DRF-001",
    availability: "in_stock",
    rating: { average: 4.4, count: 7800 },
    attributes: { color: "blue", size: "L", material: "polyester" },
    createdAt: "2024-02-05T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "23",
    name: "Instant Pot Duo 7-in-1",
    description: "Electric pressure cooker that replaces 7 kitchen appliances.",
    price: 89,
    originalPrice: 119,
    images: ["https://placehold.co/400x400?text=Instant+Pot"],
    brand: "Instant Pot",
    category: "Home",
    subcategory: "Appliances",
    sku: "INP-DUO-001",
    availability: "in_stock",
    rating: { average: 4.7, count: 45600 },
    attributes: { color: "silver", material: "steel", size: "6qt" },
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "24",
    name: "Converse Chuck Taylor All Star",
    description: "Iconic canvas sneaker with timeless style for everyday wear.",
    price: 65,
    images: ["https://placehold.co/400x400?text=Converse+Chuck"],
    brand: "Converse",
    category: "Footwear",
    subcategory: "Sneakers",
    sku: "CON-CT-001",
    availability: "in_stock",
    rating: { average: 4.5, count: 23400 },
    attributes: { color: "white", size: "41", material: "canvas" },
    createdAt: "2024-04-10T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "25",
    name: "Sony PlayStation 5",
    description: "Next-gen gaming console with ultra-high speed SSD and 4K gaming.",
    price: 499,
    images: ["https://placehold.co/400x400?text=PS5"],
    brand: "Sony",
    category: "Electronics",
    subcategory: "Gaming",
    sku: "SNY-PS5-001",
    availability: "pre_order",
    rating: { average: 4.9, count: 8900 },
    attributes: { color: "white", storage: 825, ram: 16 },
    createdAt: "2024-05-15T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
];

export const categories = Array.from(new Set(products.map((p) => p.category)));

export const ratings = Array.from(new Set(products.map((p) => Math.floor(p.rating.average))));

export const sortOptions = [
  { label: "Price: Low to High", value: "price_asc" },
  { label: "Price: High to Low", value: "price_desc" },
  { label: "Rating: High to Low", value: "rating_desc" },
  { label: "Newest Arrivals", value: "newest" },
];

export const brands = Array.from(new Set(products.map((p) => p.brand)));

export const colors = Array.from(new Set(products.map((p) => p.attributes.color)));

export function toSlug(str: string) {
  return str.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9\-]/g, "");
}

export function getProductBySlug(slug: string) {
  return products.find(p => toSlug(p.name) === slug);
}
